services:
  - type: web
    name: gofoody-ai
    env: python
    buildCommand: |
      apt-get update && apt-get install -y python3.11 python3.11-venv python3.11-distutils
      python3.11 -m venv venv
      . venv/bin/activate
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: venv/bin/gunicorn app:app
    plan: free
